spring:
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.10.124
    port: 5672
  cloud:
    gateway:
      routes:
      - id: config-server
        uri: lb://config-server:8080
        predicates:
        - Path=/config/**
        filters:
        - StripPrefix=1
