spring:
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.10.124
    port: 5672
  redis:
    database: 9
    host: 192.168.10.113
    port: 6379
    password: 123456
  zipkin:
    baseUrl: https://zipkin-server:9411/
  sleuth:
    sampler:
      percentage: 1.0
app:
  jwt:
    signKey: test-demo