security:
  oauth2:
    resource:
      id: server-demo1
      user-info-uri: http://oauth2-server/oauth2/current
      service-id: oauth2-server
spring:
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.10.124
    port: 5672